messages:
  warp_success: ""
  warp_error_not_found: ""
  warp_error_usage: ""
  setwarp_success: ""
  setwarp_error_warp_exists: ""
  setwarp_error_usage: ""
  explain_to_console_why_you_cant_warp_a_console: ""

permission:
  warp_permission: "alpsbte.warp"
  setwarp_permission: "alpsbte.moderator"
