messages:
  warp_success: ""
  warp_error_not_found: ""
  warp_error_usage: ""
  setwarp_success: ""
  setwarp_error_warp_exists: ""
  setwarp_error_usage: ""

settings:
  coutries:
    ch: "Switerland"
    au: "Austria"
    li: "lichtenstein"

permission:
  warp_permission: "alpsbte.warp"
  setwarp_permission: "alpsbte.moderator"
