name: WarpPlugin
version: ${project.version}
main: alpsbte.warp.main.Main
authors: [ DerHohii ]
description: Warp Plugin for AlpsBTE
website: alps-bte.com
commands:
  warp:
    description: Warp a player to a warp
  setwarp:
    description: Set a warp on the location of the user
  delwarp:
    description: Delete a warp

