name: WarpPlugin
version: ${project.version}
main: alpsbte.warp.main.Main
authors: [ DerHohii ]
description: Warp Plugin for AlpsBTE
website: alps-bte.com
commands:
  warp:
    description: Warp a player to a warp
    usage: /warp <name>
    permission: alpsbte.warp
  setwarp:
    description: Set a warp on the location of the user
    usage: /setwarp <name>
    permission: alpsbte.moderator
  delwarp:
    description: Delete a warp
    usage: /delwarp <name>
    permission: alpsbte.moderator
  setwarpplate:
    description: Set a Warp Plate for a given Warp
    usage: /setwarpplate <warp>
    permission: alpsbte.moderator
