name: WarpPlugin
version: ${project.version}
main: alpsbte.warp.main.Main
authors: [ AlpsBTE ]
api-version: 1.18
description: Warp Plugin for AlpsBTE
website: alps-bte.com
softdepend: [HolographicDisplays]
commands:
  warp:
    description: Warp a player to a warp
    usage: /warp <name>
    permission: alpsbte.warp
  setwarp:
    description: Set a warp on the location of the user
    usage: /setwarp <name>
    permission: alpsbte.moderator
  delwarp:
    description: Delete a warp
    usage: /delwarp <name>
    permission: alpsbte.moderator
  setwarpplate:
    description: Set a Warp Plate for a given Warp
    usage: /setwarpplate <warp>
    permission: alpsbte.moderator
  delwarpplate:
    description: Delete Warp Plate of a given Warp
    usage: /delwarpplate <warp>
    permission: alpsbte.moderator
  home:
    description: Teleport to a home
    usage: /home <name>
    permission: alpsbte.home
  sethome:
    description: Set a home
    usage: /sethome <name>
    permission: alpsbte.home
  delhome:
    description: Delete a home
    usage: /delhome <name>
    permission: alpsbte.home
  homes:
    description: list all your homes
    usage: /homes
    permission: alpsbte.home
